Algoritmo "Crescente"




Var

   x, y : inteiro
   d, c : caracter


Inicio
      escreva("Digite dois números: ")
      leia(x)
      leia(Y)
      enquanto x <> y faca
         se x > y entao
         escreval("Decrescente!")
      senao
           escreval("Crescente!")
      fimse
      escreval("Digite outro dois números: ")
        leia(x)
          leia(y)
fimenquanto




      



Fimalgoritmo