Algoritmo "Exercicio"


Var

  produto1,  produto2, genero : caractere
  preco1, preco2 : real
  idade, codigo : inteiro

Inicio

   produto1 <- "computador"
   produto2 <- "tv"
   preco1 <- 2100.5
   preco2 <- 1830.0
   idade <- 30
   codigo <- 5291
   genero <- "f"

   escreval ("Produtos")
   escreval
   escreval ("O produto ", produto1, " custa R$", preco1)
   
   Fimalgoritmo