Algoritmo "menor_de_tres"

Var
 a, b, c, d : inteiro


Inicio
      escreva("Primeiro valor: ")
      leia(a)
      escreva("Segundo valor: ")
      leia(b)
      escreva("Terceiro valor: ")
      leia(c)
      
      se (a < b) e (b < c) entao
         escreva("Menor = ", a)
      senao (a = b) e (b = c) entao
         escreva("Todos são iguais, amigo")
      fimse










Fimalgoritmo