Algoritmo "teste_natan_condicional2"



Var

   hora : inteiro
   








Inicio

      Escreval("Que horas são agora?")
      leia(hora)
      se hora < 12 entao
         escreval("Bom dia, usuário! Dormiu bem?")
      senao
           se(hora < 18) entao
              escreval("Boa tarde, usuário. Já almoçou?")
           senao
                escreval("Boa noite, usuário. Bom descanso!")
           
           fimse
      fimse








Fimalgoritmo