Algoritmo "valor da hora trabalhada"



Var
          nome : caractere
          h,v,p : real



Inicio
          Escreva("Nome do funcionário: ")
          leia(nome)
          Escreva("Valor por hora: ")
          leia(v)
          Escreva("Horas trabalhadas: ")
          leia(h)
          p <- v*h
          escreva("O pagamento para ",nome," deve ser de R$", p:8:2)

       
       
Fimalgoritmo